### ISSUE TITLE
Newer version of Data Dictionary

### ISSUE THREAD

**Issue by AlbertUlysses** [hmis-interop/logical-model#26]
Hello! I was just viewing your logical-model for a Project that I am working on with HackForLA, first I gotta say the schema you're team has made is amazing. Second, I noticed that the Data Dictionary uploaded for 2020 is actually an outdated one from August, since then an October version was released. Here is a link: https://hudhdx.info/Resources/Vendors/HMIS%20CSV%20Specifications%20FY2020%20v1.6.pdf

**Comment by eric-jahn** [comment]
Thank you @AlbertUlysses , for your feedback on the model!  Regarding the Dictionary versions, the Data Dictionary, CSV, and XSD all all different things.  The Data Dictionary is a human readable reference of all the data elements indicated, or derived from, the HUD HMIS Data Standard.  The CSV data exchange format is a normalization of the Logical Model, and the XML Schema Doc format is denormalized.  You linked me the latest CSV FY2020 v1.6, which we have had posted here: 
https://github.com/hmis-interop/logical-model/blob/master/doc/2020/HMIS-CSV.pdf (for archival purposes) .  The latest Data Dictionary, to my knowledge, is still the August one https://github.com/hmis-interop/logical-model/blob/master/doc/2020/HMIS-Data-Dictionary.pdf and also at , unless you know of  something more current (which is definitely a possibility).
Hope this helps, but mainly, best of luck on HackforLA!  -Eric

**Comment by eric-jahn** [comment]
Also, this might help: https://github.com/hmis-interop/logical-model/wiki/HMIS-Data-Standard-Versions

**Comment by AlbertUlysses** [comment]
Hey @eric-jahn thank you for the clarification, that makes way more sense. I appreciate the extra resources as well!
